name: Build Dashboard (Release)
on:
  push:
    tags:
      - v[1-9].*

jobs:
  build-validation:
    name: Validate Code
    uses: ./.github/workflows/build-test.yaml
  build:
    name: Build and Upload Package
    uses: ./.github/workflows/build-and-upload.yaml
    needs:
      - build-validation
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      CI_BUILD_TAG: ${{github.ref_name}}
  build-and-upload-docker-image:
    name: Build and Upload Docker
    uses: ./.github/workflows/build-and-upload-docker.yaml
    needs:
      - build-validation
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      CI_BUILD_TAG: ${{github.ref_name}}