name: Docker (Release)

on:
  push:
    tags:
      - v[1-9].*

jobs:
  build-and-upload-docker-image:
    name: Build and Upload
    uses: ./.github/workflows/build-and-upload-docker.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      CI_BUILD_TAG: ${{github.ref_name}}