name: Docker (Branch)

on:
  push:
    branches:
      # dev-only to remove github-actions-*
      - github-actions-*
      - master
      - 'release-*'
      - '*-dev'

jobs:
  build-and-upload-docker-image:
    name: Build and Upload
    uses: ./.github/workflows/build-and-upload-docker.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      CI_BRANCH: ${{github.ref_name}}
